### ISSUE TITLE
tests hang on Windows

### ISSUE THREAD

**Issue by chorny** [bigpresh/SMS-AQL#1]
Tests of your module hang on Windows.
I can provide more verbose information if necessary. If your module cannot work on Windows at all, you can die in Makefile.PL/Build.PL. See http://wiki.cpantesters.org/wiki/CPANAuthorNotes for how to do this.

**Comment by bigpresh** [comment]
There's no reason that the module shouldn't be able to work on Windows, so any more verbose info you can provide would be welcomed.  I don't personally use Windows, but I see no reason to deny support for Windows users unless there's a good reason, and nothing this module does is anything that wouldn't work under Windows.

**Comment by chorny** [comment]
Sometimes 1-basic.t hangs on Windows and Linux

C:\strawberry\cpan\build\SMS-AQL-1.00-fOnnr2>perl -Mblib t\1-basic.t
1..4
ok 1 - use SMS::AQL;
ok 2 - Create instance of SMS::AQL
ok 3 - $sender is an instance of SMS::AQL
(hangs)

c@deb1:~/.cpan/build/SMS-AQL-1.00-UuT6Ht$ perl -Mblib t/1-basic.t
1..4
ok 1 - use SMS::AQL;
ok 2 - Create instance of SMS::AQL
ok 3 - $sender is an instance of SMS::AQL
(hangs)

**Comment by pink-mist** [comment]
I just installed it without issue via cpan on cygwin with perl 5.10.1:

```
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for SMS::AQL
Writing MYMETA.yml and MYMETA.json
cp lib/SMS/AQL.pm blib/lib/SMS/AQL.pm
Manifying 1 pod document
  BIGPRESH/SMS-AQL-1.01.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/1-basic.t ......... ok
t/2-pod.t ........... ok
t/3-pod-coverage.t .. ok
t/4-mock.t .......... skipped: Test::MockObject::Extends required for mock testing
All tests successful.
Files=4, Tests=6,  2 wallclock secs ( 0.08 usr  0.03 sys +  0.57 cusr  0.53 csys =  1.21 CPU)
Result: PASS
  BIGPRESH/SMS-AQL-1.01.tar.gz
  /usr/bin/make test -- OK
Running make install
Prepending /home/Andreas/.cpan/build/SMS-AQL-1.01-GeWoN9/blib/arch /home/Andreas/.cpan/build/SMS-AQL-1.01-GeWoN9/blib/lib to PERL5LIB for 'install'
Manifying 1 pod document
Installing /usr/lib/perl5/site_perl/5.10/SMS/AQL.pm
Installing /usr/share/man/man3/SMS.AQL.3pm
Appending installation info to /usr/lib/perl5/5.10/i686-cygwin/perllocal.pod
  BIGPRESH/SMS-AQL-1.01.tar.gz
  /usr/bin/make install  -- OK
```

**Comment by chorny** [comment]
I think it was buggy version of LWP, I have upgraded it on my smokers since then.
